version: '3'
services:
  haensl.github.io:
    build: .
    image: hpd/haensl.github.io:2.42.3
    container_name: 'haensl.github.io'
    networks:
      - io.github.haensl
    restart: unless-stopped

networks:
  io.github.haensl:
    external: true
