version: '3'
services:
  haensl.github.io:
    build: .
    image: registry.gitlab.com/hpd/haensl.github.io.src:$VERSION
    container_name: 'io.github.haensl'
    networks:
      - io.github.haensl
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8081

networks:
  io.github.haensl:
    external: true
